name: unifiedpush_storage
description: UnifiedPush Storage
version: 0.1.0
homepage: "https://unifiedpush.org/developers/flutter"
documentation: "https://unifiedpush.org/developers/flutter"
repository: https://codeberg.org/UnifiedPush/flutter-connector/src/branch/main/unifiedpush_storage

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  unifiedpush_storage_interface: ^0.1.0
  shared_preferences: ^2.2.1

dependency_overrides:
  unifiedpush_storage_interface:
    path: ../unifiedpush_storage_interface
