name: unifiedpush_linux
description: Linux implementation of UnifiedPush plugin.
version: 0.0.3
homepage: "https://unifiedpush.org/developers/flutter"
documentation: "https://unifiedpush.org/developers/flutter"
repository: https://codeberg.org/UnifiedPush/flutter-connector/src/branch/main/unifiedpush_linux

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  unifiedpush_platform_interface: ^3.0.0
  dbus: ^0.7.11
  shared_preferences: ^2.2.1
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    implements: unifiedpush
    platforms:
      linux:
        dartPluginClass: UnifiedpushLinux

#dependency_overrides:
#  unifiedpush_platform_interface:
#    path: ../unifiedpush_platform_interface
