name: unifiedpush_ui
description: UnifiedPush Dialogs
version: 0.1.0
homepage: "https://unifiedpush.org/developers/flutter"
documentation: "https://unifiedpush.org/developers/flutter"
repository: https://codeberg.org/UnifiedPush/flutter-connector/src/branch/main/unifiedpush_ui

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.11

dev_dependencies:
  dependency_validator: ^4.0.0 # Keep 4+ to avoid increasing min SDK.
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Keep 4+ to avoid increasing min SDK.
