version: 2
updates:
- package-ecosystem: gradle
  directory: "/android"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/example/android"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
